enemy_index = 0 // Will be set when created
data = {}
sprite_index = spr_enemy
xstart = x
ystart = y
sprite_offset = 0
is_hovered = false
displayed_hp = 0
current_sprite = sprite_index  
animation_timer = 0            